<<<<<<< HEAD
version: "3.9"

services:
  # Backend Flask
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://admin:admin123@db:5432/dbdit
    networks:
      - dit-network

  # Frontend React (Vite)
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - dit-network

  # PostgreSQL
  db:
    image: postgres:16
=======
version: "3"

services:

  postgres_server:
    image: postgres:15
>>>>>>> a7a7234 (envoie du fichier jenkins et du docket compose, et mise a jour du readme complet)
    container_name: postgres_server
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: dbdit
<<<<<<< HEAD
    ports:
      - "5432:5432"
    volumes:
      - ditdata:/var/lib/postgresql/data
    networks:
      - dit-network

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - dit-network

# Volume pour PostgreSQL
volumes:
  ditdata:

# Réseau commun
networks:
  dit-network:
=======
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - biblio_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d dbdit"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://admin:admin123@postgres_server:5432/dbdit
    depends_on:
      postgres_server:
        condition: service_healthy
    networks:
      - biblio_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - biblio_network

volumes:
  postgres_data:

networks:
  biblio_network:
>>>>>>> a7a7234 (envoie du fichier jenkins et du docket compose, et mise a jour du readme complet)
    driver: bridge
